version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: hobbie-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=hobbie_backend_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springmysql-net
    restart: unless-stopped

  spring-backend:
    build: .
    container_name: hobbie-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hobbie_backend_db?useSSL=false&serverTimezone=Europe/Paris&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1
    depends_on:
      - mysql
    networks:
      - springmysql-net
    restart: unless-stopped

networks:
  springmysql-net:
    driver: bridge

volumes:
  mysql-data: